version: '3'

includes:
  ci:
    taskfile: ./Taskfile_CI.yml

tasks:
  install:
    desc: Install Pre-requisites
    summary: Installs the various tools needed to work with this project
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

  lint:
    desc: Code Linting
    summary: Lint the project files with golangci-lint
    cmds:
      - golangci-lint run -c .golangci.yml

  format:
    desc: Run 'goimports' to format go imports
    summary: Runs goimports on all files with -local support, can also replace gofmt
    cmds:
      - goimports -local github.com/circleci/policy-service -w .

  test:
    desc: Run the tests
    cmds:
      - go test ./... -race -count 1

  go-mod-tidy:
    desc: Run 'go mod tidy' to clean up module files.
    cmds:
      - go mod tidy -v

  doc:
    desc: Run 'godoc', print docs url
    cmds:
      - |
        godoc &
        echo 'docs are open at:'
        echo 'http://localhost:6060/pkg/github.com/circleci/policy-agent/'
        wait

  doc-open:
    desc: Run 'godoc', open the docs url in your browser
    cmds:
      - sleep .5 && open 'http://localhost:6060/pkg/github.com/circleci/policy-agent/' &
      - task: doc

  check-go-mod:
    desc: Check go.mod is tidy
    cmds:
      - go mod tidy -v
      - git diff --exit-code -- go.mod go.sum
  
  create-mocks:
    desc: generate mocks
    cmds:
      - ./genmocks.sh